### ISSUE TITLE
Is the example complete?

### ISSUE THREAD

**Issue by rgb1380** [AgoraLibrary/flutter_agora_rtc_rawdata#1]
I imagine the intent of this plug-in is to allow access to video/audio frame raw data. The example, however, registers the audio and video frame observers but does not show include any callback to access frame data. Is the example complete? Can this plug-in be used?

**Comment by LichKing-2234** [comment]
the raw data observer at native layer

**Comment by LichKing-2234** [comment]
it just export register or unregister method to dart layer

**Comment by rgb1380** [comment]
How can this be used?

**Comment by LichKing-2234** [comment]
I have updated the readme, you can refer to it.

**Comment by rgb1380** [comment]
Great. Thanks.

**Comment by bmabir17** [comment]
> You should fork this repository, and modify the code to implement your requirement, such as use third-party beauty SDK.

@LichKing-2234 So I should make my preprocessing changes in place of the following line and publish another package?
https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/blob/b74d013fa79a56c0e662412c71bdc18f3a3ad4a2/android/src/main/kotlin/io/agora/agora_rtc_rawdata/AgoraRtcRawdataPlugin.kt#L67-L68

**Comment by LichKing-2234** [comment]
@bmabir17 The best way is to fork this plugin and use yours.
