### ISSUE TITLE
Asynchronous Support

### ISSUE THREAD

**Issue by mirrorlink** [AgoraLibrary/flutter_agora_rtc_rawdata#10]
Hello. 

The function onCaptureVideoFrame seems to be synchonous. That mean I wouldnt be able to use any asynchonous function like, for example, com.google.mlkit.vision.face.FaceDetector to detect faces:

```
override fun onCaptureVideoFrame(videoFrame: VideoFrame): Boolean {
              Arrays.fill(videoFrame.getuBuffer(), 0)
              Arrays.fill(videoFrame.getvBuffer(), 0)
              return true
            }
```

Don't we need a consumer object for this situations? How can I make the frame ready ascynchronously?

just like the

```
var consumer: AgoraVideoFrameConsumer
```

Thank you!

**Comment by LichKing-2234** [comment]
It must be sync.

**Comment by mirrorlink** [comment]
Why?

**Comment by mirrorlink** [comment]
> It must be sync.

why?

**Comment by mirrorlink** [comment]
> It must be sync.

Can I run it with Tasks.await ? Does it run on the UI thread?
