### ISSUE TITLE
ios_agora_rtc_engine4.0.7本地和对方视频流都调用了onRenderVideoFrame

### ISSUE THREAD

**Issue by qja2004** [AgoraLibrary/flutter_agora_rtc_rawdata#13]
您好，我升级了agora_rtc_engine4.0.7，在ios测试时，使用onRenderVideoFrame处理对方AgoraVideoFrame，但本地的和对方的都调用了这个方法。
有只调用对方视频流或者区分出对方的视频的方法吗？

**Comment by qja2004** [comment]
> 您好，我升级了agora_rtc_engine4.0.7，在ios测试时，使用onRenderVideoFrame处理对方AgoraVideoFrame，但本地的和对方的都调用了这个方法。 有只调用对方视频流或者区分出对方的视频的方法吗？

使用agora_rtc_engine 4.1.0-alpha.2却又正常了

**Comment by LichKing-2234** [comment]
可能是 特定native版本的问题？建议pod依赖不同的native SDK测试下

**Comment by LichKing-2234** [comment]
Native 3.5.0.3的bug
