### ISSUE TITLE
How to migrate to 6.0.0?

### ISSUE THREAD

**Issue by vakrolme** [AgoraLibrary/flutter_agora_rtc_rawdata#16]
I'm trying to migrate a project that depends on this plugin to the 6.0.0-beta.1 version of Flutter SDK, without losing Raw Data functionality.

In 6.0.0, the `RtcEngine` class in Dart doesn't seem to have `getNativeHandle()` method anymore, and probably there are a few other things that need to be changed in this repo to make it work with the new SDK NG.

What are the necessary changes to perform a migration?

**Comment by LichKing-2234** [comment]
This plugin is only for https://github.com/AgoraIO/Agora-Flutter-SDK. We have a plan to support it on 6.+ version.

**Comment by vakrolme** [comment]
@LichKing-2234 great! Can you share more details on that? Perhaps there's an ETA estimate that I could plan around?

**Comment by thosonit** [comment]
@LichKing-2234 Recently, `agora_rtc_engine: ^6.1.0` added `getNativeHandle()` function and I think we can upgrade this plugin with the newest `agora_rtc_engine` package.

**Comment by LichKing-2234** [comment]
Sorry, this plugin is legacy, you can refer to https://github.com/AgoraIO-Extensions/RawDataPluginSample/tree/main/frameworks/flutter/video_raw_data

**Comment by littleGnAl** [comment]
I have updated the code to support `agora_rtc_engine: 6.1.0`.
https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/pull/18
