### ISSUE TITLE
Bug in Android when unregisterVideoFrameObserver

### ISSUE THREAD

**Issue by NamHofstadter** [AgoraLibrary/flutter_agora_rtc_rawdata#17]
![image](https://user-images.githubusercontent.com/26591903/204426214-d38853e6-8195-4a3f-9d4f-01d4a8aa45ad.png)

**Comment by NamHofstadter** [comment]
@littleGnAl @LichKing-2234 @uzawa-gmo 
Do I fix it? 
![image](https://user-images.githubusercontent.com/26591903/204426656-f90a9e7f-933a-4f1d-8543-b6ed9b5346ae.png)

**Comment by LichKing-2234** [comment]
it has been fixed
