### ISSUE TITLE
请问如何将VideoFrame里的数据转换成图片。

### ISSUE THREAD

**Issue by gooljim** [AgoraLibrary/flutter_agora_rtc_rawdata#2]
目前的VideoFrame的 数据包括了Y U V三个数组，如何合并这些数据生成一张图片，非常感谢

**Comment by LichKing-2234** [comment]
重写`getVideoFormatPreference`方法，返回`VideoFrameType.RGBA`，就可以从`yBuffer`中获取**RGBA**的字节数据了

**Comment by LichKing-2234** [comment]
或者参考我们的原生demo，里面有相关转换代码。
https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/ProcessRawData.java

**Comment by gooljim** [comment]
> 或者参考我们的原生demo，里面有相关转换代码。
> https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/ProcessRawData.java

感谢

**Comment by gooljim** [comment]
@LichKing-2234 很抱歉，因为对图片这块不熟悉，是否可以提供一份RGBA字节或者YUV三向量转化图片的方法，您发的方法我也看了，但是没找到有用的方式，谢谢

**Comment by LichKing-2234** [comment]
有看到这个方法么`YUVUtils.i420ToBitmap`？

**Comment by gooljim** [comment]
> 有看到这个方法么`YUVUtils.i420ToBitmap`？

看到了，但是这个接口里输入参数是byte[] data，请教如何将VideoFrame里  byte[] yBuffer，byte[] uBuffer， byte[] vBuffer转成成对应输入参数，非常感谢~

**Comment by LichKing-2234** [comment]
网上很多YUV合并的代码，demo是在c++合并的

https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/lib-raw-data/src/main/cpp/io_agora_advancedvideo_rawdata_MediaPreProcessing.cpp#L65

**Comment by LichKing-2234** [comment]
你可以参考着改下，这个插件你可以随意定制

**Comment by gooljim** [comment]
@LichKing-2234 我重写getVideoFormatPreference方法，返回VideoFrameType.RGBA，但是截图出来后，图片颜色带灰度
`    val bmp = Bitmap.createBitmap(videoFrame.width, videoFrame.height, Bitmap.Config.ARGB_8888)
                        bmp.setPixels(btoi(videoFrame.getyBuffer()), 0, videoFrame.width, 0, 0, videoFrame.width, videoFrame.height)
                        bmp?.compress(Bitmap.CompressFormat.JPEG, 80, fos)`

**Comment by LichKing-2234** [comment]
你可以找个工具，看下原始字节是不是带灰度的
