### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by gupisys** [AgoraLibrary/flutter_agora_rtc_rawdata#3]
## Abstract
I cloned the repository and ran the example Flutter app, but it does not work. I suppose the observer functions such as `onCaptureVideoFrame` are not called.

## Detail
The README says the plugin will change the local video to green, and I can confirm that the documentation is correct according to [these lines (code)](https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/blob/b74d013fa79a56c0e662412c71bdc18f3a3ad4a2/android/src/main/kotlin/io/agora/agora_rtc_rawdata/AgoraRtcRawdataPlugin.kt#L67-L68).
However, running the app in the Android emulator (API 30) and my Android smartphone (Android 11), no changes in local and remote video were observed.

Of course I have called `registerAudioFrameObserver `and `registerVideoFrameObserver `in `_initEngine()` just like the README usage example.
After my printf-debugging, it seems like observer functions like `onCaptureVideoFrame` are not called though `registerVideoFrameObserver` was surely called.

Raw data capturing is critical to my project, and I would be happy if you could help me with this.

**Comment by LichKing-2234** [comment]
this plugin is outdated, we have a plan to upgrade it. you can only use `agora_rtc_engine:3.2.0`.

**Comment by LichKing-2234** [comment]
which version of `agora_rtc_engine` have you used?

**Comment by gupisys** [comment]
Thank you for your reply!
It is `3.3.3`

**Comment by LichKing-2234** [comment]
you should use 3.2.+, if you want to use another version, you should replace the [header files](https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/tree/master/cpp/android/include) for the Android platform.

**Comment by gupisys** [comment]
Editing pubspec.yaml to use 3.2.0 of agora_rtc_engine solved the issue.
I sincerely appreciate your work.

**Comment by florianthiel** [comment]
> you should use 3.2.+, if you want to use another version, you should replace the [header files](https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/tree/master/cpp/android/include) for the Android platform.

Where can I find the correct header files for the newest version?

**Comment by LichKing-2234** [comment]
@florianthiel you can download and unzip the SDK.
https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_v3_4_5_FULL.zip

if you want to download the special version, such as 3.3.0, you can use:
https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_v3_3_0_FULL.zip
