### ISSUE TITLE
只要一注册这个监听，本地预览变成绿色，对方图像变成粉色了，怎么破，flutter的agoraSdk版本4.0.5

### ISSUE THREAD

**Issue by NamHofstadter** [AgoraLibrary/flutter_agora_rtc_rawdata#4]
rt

**Comment by NamHofstadter** [comment]
文档里说这是默认的，但是我把Arrays代码移除后，仍然是绿色+粉色，请问怎么去除？

**Comment by LichKing-2234** [comment]
去除后有重新运行原生部分么

**Comment by NamHofstadter** [comment]
> 去除后有重新运行原生部分么

有的，Android环境，Native代码clean后重新build，都无法去除。
目前解除了yaml依赖，cpp、native、flutter代码均使用源码集成，然后在Android端手动注册plugin，然后再移除绿色代码，就是有效果的

**Comment by NamHofstadter** [comment]
不是移除代码没执行，而是整个plugin的回调都没执行，因为使用yaml依赖后，Android端会自动在GeneratedPluginRegistrant中注册plugin，而这个plugin是demo里的plugin，所以自己再写一个plugin是没有用的，无论怎么改都不会执行

**Comment by NamHofstadter** [comment]
所以这个插件的集成方式可能要改一下，应该移除插件自动注册逻辑，增加手动注册的说明

**Comment by LichKing-2234** [comment]
是的，我们这个只是一个示例，需要您fork后自定义逻辑，不是直接依赖pub.dev上的library。

**Comment by NamHofstadter** [comment]
> 是的，我们这个只是一个示例，需要您fork后自定义逻辑，不是直接依赖pub.dev上的library。

原来如此
