### ISSUE TITLE
升级了flutter2.5.2后，ios环境运行demo报错architecture arm64

### ISSUE THREAD

**Issue by qja2004** [AgoraLibrary/flutter_agora_rtc_rawdata#8]
您好，我在升级了flutter2.5.2，运行demo报错architecture arm64， clang: error: linker command failed with exit code，即使在pods的agora_rtc_engine下的exclude architectures增加arm64，仍然报此错误，很困惑
![Uploading 5701636962874_.pic_hd.jpg…]()

**Comment by LichKing-2234** [comment]
Pls try to set `Validate Workspace` to Yes

![image](https://user-images.githubusercontent.com/9312526/141749420-01d20610-658c-493a-b86c-a3620ef111f9.png)

**Comment by qja2004** [comment]
清理一下，真机可以运行正常，模拟器不能运行。
应该是agora_rtc_engine在flutter2.5.2生成pods时，影响模拟器arm64的支持。
感谢

**Comment by adfdev** [comment]
Any solution for simulator?

**Comment by LichKing-2234** [comment]
@adfdev do this then run it with Xcode, not `flutter run`

> Pls try to set `Validate Workspace` to Yes
> 
> ![image](https://user-images.githubusercontent.com/9312526/141749420-01d20610-658c-493a-b86c-a3620ef111f9.png)

**Comment by adfdev** [comment]
> @adfdev do this then run it with Xcode, not `flutter run`
> 
> > Pls try to set `Validate Workspace` to Yes
> > ![image](https://user-images.githubusercontent.com/9312526/141749420-01d20610-658c-493a-b86c-a3620ef111f9.png)

Even running with xcode I always get the same error, the following:

```
building for iOS Simulator, but linking in dylib built for iOS, file '/Users/mac/Desktop/test-app/ios/Pods/AgoraRtcEngine_iOS/AgoraJNDExtension.framework/AgoraJNDExtension' for architecture arm64
```

**Comment by LichKing-2234** [comment]
Could you pls share the screenshot about the `Validate Workspace`? It works for me.

**Comment by adfdev** [comment]
My solution work for me:

[This guide](https://amala-gopal.medium.com/building-for-ios-simulator-but-linking-in-dylib-built-for-ios-file-for-architecture-arm64-a200bc991735) after that run:

1. delete pods folder
2. delete podfile.lock
3. run pod install
4. run flutter clean
5. run flutter pub get
6. flutter run

Now I obtain this following error:

```
/Users/mac/Desktop/app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'agora_rtc_engine' not found
    @import agora_rtc_engine;
```

**note:** have this above error only in ios simulator, with physical device it can run

**Comment by zionnite** [comment]
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end
```
