### ISSUE TITLE
More Meaningful Example

### ISSUE THREAD

**Issue by mirrorlink** [AgoraLibrary/flutter_agora_rtc_rawdata#9]
Hello. Can I have an example of how to use  this package.

The example contained is of just two lines 
```
override fun onCaptureVideoFrame(videoFrame: VideoFrame): Boolean {
              Arrays.fill(videoFrame.getuBuffer(), 0)
              Arrays.fill(videoFrame.getvBuffer(), 0)
              return true
            }
```

I need more examples of how to convert VideoFrame to Java byte array or to a Java Bitmap, and also from java bitmap

Thank you!

**Comment by mirrorlink** [comment]
[Masks.zip](https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/files/7872293/Masks.zip)

If anyone ever finds this, here is a ZIP containing a full example of how to use masks on agoraio with face detection by MLKIT

It uses these libs to convert from and to YUV420

https://cocoapods.org/pods/libyuv-iOS
https://github.com/crow-misia/libyuv-android

**Comment by LichKing-2234** [comment]
Thanks!
